about/__init__.py
from flask import Blueprint

about = Blueprint('about', __name__)

from . import views

about/views.py
from flask import render_template
from database_mongo.database import db
from database_postgres.database import cursor
from auth.views import get_username, get_isadmin, get_role
from . import about
    

@about.route('/employees', methods=['GET', 'POST'])
def employees():
    cursor.execute("SELECT * FROM employee ORDER BY employee_id ASC ")
    employees = cursor.fetchall()
    cursor.execute("SELECT * FROM department WHERE department_id != 'NONE' ORDER BY department_id ASC")
    departments = cursor.fetchall()
    return render_template('about/employees.html', title='Employees', employees = employees, departments = departments, username = get_username(), isadmin = get_isadmin(), role = get_role())

@about.route('/about/<user>', methods=['GET', 'POST'])
def about(user):
    emp = db.employee.find_one({"_id" : user})
    
    # basic_pay=emp['basic_pay']
    # contact_no=emp['contact_no']
    # print(first_name)

    # for order in emp:
    #     print(order)
    first_name = emp['first_name']
    last_name = emp['last_name']
    email_id = emp['email_id']
    department_id = emp['department_id']
    no_awards = emp['no_awards']
    no_publications = emp['no_publications']
    no_researchs = emp['no_researchs']
    no_projects = emp['no_projects']
    biography = emp['biography']
    
    education = emp['education']
    experience = emp['experience']
    research_interests = emp['research_interests']
    projects = emp['projects']
    awards = emp['awards']
    publications = emp['publications']

    return render_template('about/employee.html', first_name = first_name, last_name = last_name, email_id = email_id, department_id = department_id, 
                        no_awards = no_awards, no_publications = no_publications, no_researchs = no_researchs, no_projects = no_projects,
                        biography = biography, education = education, experience = experience, research_interests = research_interests,
                        projects = projects, publications = publications, awards = awards, title='About', username = get_username(), isadmin = get_isadmin(), role = get_role())

templates/about/employee.html
{% extends "base.html" %}
{% block title %}{{ first_name }} {{ last_name }}{% endblock %}
{% block body %}
	<div id="colorlib-page">
		<div class="container-wrap">
		<a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"><i></i></a>
		<aside id="colorlib-aside" role="complementary" class="border js-fullheight">
			<div class="text-center">
				<div class="author-img" style="background-image: url(/static/img/about.png);"></div>
				<h1 id="colorlib-logo"><a>{{first_name}} {{last_name}}</a></h1>
				<span class="position">{{department_id}}</span>
			</div>
			<nav id="colorlib-main-menu" role="navigation" class="navbar">
				<div id="navbar" class="collapse">
					<ul>
						<li><a href="#" data-nav-section="about">About Me!</a></li>
						{% if research_interests %}
						<li><a href="#" data-nav-section="interests">Interests</a></li>
						{% endif %}
						{% if education or experience %}
						<li><a href="#" data-nav-section="edu_work">Education/Experience</a></li>
						{% endif %}
						{% if publications %}
						<li><a href="#" data-nav-section="publications">Publications</a></li>
						{% endif %}
						{% if projects %}
						<li><a href="#" data-nav-section="projects">Projects</a></li>
						{% endif %}
						{% if awards %}
						<li><a href="#" data-nav-section="awards">Awards</a></li>
						{% endif %}
					</ul>
				</div>
			</nav>
		</aside>

		<div id="colorlib-main">
			<!-- Biography -->
			<section class="colorlib-about" data-section="about">
				<div class="colorlib-narrow-content">
					<div class="row">
						<div class="col-md-12">
							<div class="row row-bottom-padded-sm animate-box" data-animate-effect="fadeInLeft">
								<div class="col-md-12">
									<div class="about-desc">
										<span class="heading-meta">About Me!</span>
										<h2 class="colorlib-heading">{{first_name}} {{last_name}}</h2>
										<span class="heading-meta">Department : {{department_id}}</span>
										<span class="heading-meta">Email Id : {{email_id}}</span>
										<span class="heading-meta">DA : {{"28%"}}</span>
										<span class="heading-meta">TA : {{"7200"}}</span>
										<span class="heading-meta">HRA : {{"18%"}}</span></span><p><br></p>
										<!-- <span class="heading-meta">NPS : {{email_id}}</span><p><br></p> -->
										{% if biography %}
										<p>{{biography}}</p>
										{% endif %}
											<!-- Add email-id and department -->
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>


			<!-- Interests -->
			{% if research_interests %}
			<section class="colorlib-services" data-section="interests">
				<div class="colorlib-narrow-content">
					<div class="row">
						<div class="col-md-6 col-md-offset-3 col-md-pull-3 animate-box" data-animate-effect="fadeInLeft">
							<span class="heading-meta">Interests!</span>
							<h2 class="colorlib-heading">Current Research Interests</h2>
						</div>
					</div>

					{% for ri in research_interests %}
					<div class="row row-pt-md">
						<div class="col-md-4 text-center animate-box">
							<div class="services color-1">
								<span class="icon">
									<i class="icon-data"></i>
								</span>
								<div class="desc">
									<p> {{ri}} </p>
								</div>
							</div>
						</div>
					</div>
					{% endfor %}
				</div>
			</section>
			{% endif %}
			
			<div id="colorlib-counter" class="colorlib-counters" style="background-image: url(/static/img/cover_bg_1.jpg);" data-stellar-background-ratio="0.5">
				<div class="overlay"></div>
				<div class="colorlib-narrow-content">
					<div class="row">
					</div>
					<div class="row">

						{% if no_projects > 0 %}
						<div class="col-md-3 text-center animate-box">
							<span class="colorlib-counter js-counter" data-from="0" data-to={{no_projects}} data-speed="5000" data-refresh-interval="50"></span>
							<span class="colorlib-counter-label">Projects</span>
						</div>
						{% endif %}

						{% if no_publications > 0 %}
						<div class="col-md-3 text-center animate-box">
							<span class="colorlib-counter js-counter" data-from="0" data-to={{no_publications}} data-speed="5000" data-refresh-interval="50"></span>
							<span class="colorlib-counter-label">Publications</span>
						</div>
						{% endif %}

						{% if no_researchs > 0 %}
						<div class="col-md-3 text-center animate-box">
							<span class="colorlib-counter js-counter" data-from="0" data-to={{no_researchs}} data-speed="5000" data-refresh-interval="50"></span>
							<span class="colorlib-counter-label">Research Output</span>
						</div>
						{% endif %}

						{% if no_awards > 0 %}
						<div class="col-md-3 text-center animate-box">
							<span class="colorlib-counter js-counter" data-from="0" data-to={{no_awards}} data-speed="5000" data-refresh-interval="50"></span>
							<span class="colorlib-counter-label">Awards</span>
						</div>
						{% endif %}
					</div>
				</div>
			</div>


			<!-- Education/Experience -->
			{% if education or experience %}
			<section class="colorlib-education" data-section="edu_work">
				<div class="colorlib-narrow-content">
					<div class="row">
						<div class="col-md-6 col-md-offset-3 col-md-pull-3 animate-box" data-animate-effect="fadeInLeft">
							<span class="heading-meta">Education/Experience</span>
							{% if education %}
							<h2 class="colorlib-heading animate-box"> &nbsp; Education</h2>
							{% endif %}
						</div>
					</div>

					<!-- Education Section -->
					{% if education %}
					<div class="row">
						<div class="col-md-12 animate-box" data-animate-effect="fadeInLeft">
							<div class="fancy-collapse-panel">
								<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
									
									{% for ed in education %}
									<div class="panel panel-default">
									    <div class="panel-heading" role="tab" id="headingThree">
									        <h4 class="panel-title">
									            <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">{{ ed }}
									            </a>
									        </h4>
									    </div>
									</div>
									{% endfor %}

								</div>
							</div>
						</div>
					</div>
					{% endif %}

					<!-- Experience -->
					{% if experience %}
					<p><br><br></p>
					<div class="col-md-6 col-md-offset-3 col-md-pull-3 animate-box" data-animate-effect="fadeInLeft">
						
							<h2 class="colorlib-heading animate-box">&nbsp;Experience</h2>
							
					</div>

					<div class="row">
						<div class="col-md-12 animate-box" data-animate-effect="fadeInLeft">
							<div class="fancy-collapse-panel">
								<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
									
									{% for ex in experience %}
									<div class="panel panel-default">
										<div class="panel-heading" role="tab" id="headingThree">
											<h4 class="panel-title">
												<a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">{{ ex }}
												</a>
											</h4>
										</div>
									</div>
									{% endfor %}

								</div>
							</div>
						</div>
					</div>
					{% endif %}
				</div>
			</section>
			{% endif %}


			<!-- Publications -->
			{% if publications %}
			<section class="colorlib-blog" data-section="publications">
				<div class="colorlib-narrow-content">
					<div class="row">
						<div class="col-md-6 col-md-offset-3 col-md-pull-3 animate-box" data-animate-effect="fadeInLeft">
							<span class="heading-meta">Publications</span>
							<h2 class="colorlib-heading">My Publications</h2>
						</div>
					</div>
					<div class="row">

						{% for pu in publications %}
						<div class="col-md-4 col-sm-6 animate-box" data-animate-effect="fadeInRight">
							<div class="blog-entry">
								<div class="desc">
									<h3><a> {{ pu }}</a></h3>
								</div>
							</div>
						</div>
						{% endfor %}

					</div>
				</div>
			</section>
			{% endif %}

			{% if projects %}
			<section class="colorlib-blog" data-section="projects">
					<div class="colorlib-narrow-content">
						<div class="row">
							<div class="col-md-6 col-md-offset-3 col-md-pull-3 animate-box" data-animate-effect="fadeInLeft">
								<span class="heading-meta">Projects</span>
								<h2 class="colorlib-heading">My Projects</h2>
							</div>
						</div>
						<div class="row">
	
							{% for pr in projects %}
							<div class="col-md-4 col-sm-6 animate-box" data-animate-effect="fadeInRight">
								<div class="blog-entry">
									<div class="desc">
										<h3 ><a> {{ pr }}</a></h3>
									</div>
								</div>
							</div>
							{% endfor %}
						</div>
	
						
					</div>
				</section>
			{% endif %}

			<!-- Awards -->
			{% if awards %}
			<section class="colorlib-experience" data-section="awards">
				<div class="colorlib-narrow-content">
					<div class="row">
						<div class="col-md-6 col-md-offset-3 col-md-pull-3 animate-box" data-animate-effect="fadeInLeft">
							<span class="heading-meta">Awards</span>
							<h2 class="colorlib-heading animate-box">My Prizes</h2>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<div class="timeline-centered">

							{% for aw in awards %}
								<article class="timeline-entry animate-box" data-animate-effect="fadeInLeft">
								<div class="timeline-entry-inner">
									<div class="timeline-icon color-1">
										<i class="icon-pen2"></i>
									</div>
									<div class="timeline-label">
										<p><a>{{ aw }}</p>
									</div>
								</div>
								</article>
								{% endfor %}

								<article class="timeline-entry begin animate-box" data-animate-effect="fadeInBottom">
									<div class="timeline-entry-inner">
										<div class="timeline-icon color-none">
										</div>
									</div>
								</article>
							</div>
						</div>
					</div>
				</div>
			</section>
			{% endif %}
		</div><!-- end:colorlib-main -->
	</div><!-- end:container-wrap -->
{% endblock %}

templates/about/employees.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Departments{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        {% if employees %}
        <h1 style="text-align:center;">Cross Cutting Faculties and HOD</h1>
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                        <th width="15%"> Employee-ID </th>
                        <th width="10%"> Role</th>
                  <th width="18%"> First Name </th>
                  <th width="18%"> Last Name </th>
                  <th width="10%"> Basic Pay </th>
                </tr>
              </thead>
              <tbody>
              {% for employee in employees %}
              {% if employee[9] != 'FACULTY' %}
                <tr>
                        
                  <td> <a href="{{ url_for('about.about', user = employee[0]) }}">{{ employee[0] }} </a></td>
                  <td> {{ employee[7] }} </td>
                <td> {{ employee[2] }} </td>
                <td> {{ employee[3] }} </td>
                  <td> {{ employee[5] }} </td>
                  
                </tr>
              {% endif %}
              {% endfor %}
              </tbody>
            </table>
            <p><br><br><br></p>

            <h1 style="text-align:center;">Faculties</h1>

            <hr class="intro-divider">
            {% for d in departments %}
            <h1 style="text-align:center;">{{ d[1] }}</h1>
          <hr class="intro-divider">
          <!-- <div class="center"> -->
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                <th width="15%"> Employee-ID </th>
                  <th width="18%"> First Name </th>
                  <th width="18%"> Last Name </th>
                </tr>
              </thead>
              <tbody>
              {% for employee in employees %}
              {% if employee[7] == d[0] %}
                <tr>
                        
                  <td> <a href="{{ url_for('about.about', user = employee[0]) }}">{{ employee[0] }}</a> </td>
                <td> {{ employee[2] }} </td>
                <td> {{ employee[3] }} </td>
                </a>
                </tr>
              {% endif %}
              {% endfor %}
              </tbody>
            </table>
        <p><br><br></p>
      {% endfor %}
        </div>
        </div>
        <div style="text-align: center">
                {% else %}
                  <div style="text-align: center">
                    <h3> No employees have been added. </h3>
                    <hr class="intro-divider">
                {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}