user/forms.py
from flask_wtf import FlaskForm
from datetime import date
from wtforms import PasswordField, StringField, SubmitField, ValidationError, DateField, SelectField, TextAreaField, TextField, IntegerField
from wtforms.validators import DataRequired, EqualTo
from wtforms.fields.html5 import DateField

class LeaveApplicationForm(FlaskForm):
    start_date = DateField('Start Date', validators=[DataRequired()], format='%Y-%m-%d')
    end_date = DateField('End Date', validators=[DataRequired()], format='%Y-%m-%d')
    leave_type = SelectField('Leave Type', choices = [('Regular', 'Regular'),('Borrowing','Borrow from Next Year')])
    application = TextAreaField('Application', validators=[DataRequired()])
    submit = SubmitField('Apply for Leave!')

class commentFormLower(FlaskForm):
    comment = TextAreaField('Comment')
    submit = SubmitField('Submit!')

class commentFormHigher(FlaskForm):
    comment = TextField('Comment')
    action = SelectField('Action', choices = [('forward','Grant/Forward'),('reject','Reject'),('send_back','Send Back')])
    submit = SubmitField('Submit!')

class EditDetailsForm(FlaskForm):
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    email_id = StringField('Email ID', validators=[DataRequired()])
    biography = TextAreaField('Biography')
    no_awards = IntegerField('Awards Won')
    no_publications = IntegerField('Total Publications')
    no_researchs = IntegerField('Reseach Output')
    no_projects = IntegerField('Projects Done')
    submit = SubmitField('Save Changes')

class AddDetailsForm(FlaskForm):
    add = TextField('Specification', validators=[DataRequired()])
    submit = SubmitField('Save Changes')

user/__init__.py
from flask import Blueprint

user = Blueprint('user', __name__)

from . import views

user/views.py
import datetime
from . import user
from database_mongo.database import db
from auth.views import get_username, get_isadmin, get_role
from database_postgres.database import cursor, conn
from flask import abort, flash, redirect, render_template, url_for
from user.forms import LeaveApplicationForm, EditDetailsForm, commentFormLower, commentFormHigher, AddDetailsForm


@user.route('/dashboard', methods=['GET', 'POST'])
def dashboard():
    if (get_username() == ""):
        flash ("Please Login!")
        return redirect(url_for('auth.login'))
    return render_template('/user/dashboard.html', title = "Dashboard", username = get_username(), isadmin = get_isadmin(), role = get_role())

@user.route('/application', methods=['GET', 'POST'])
def new_application():
    if (get_username() == ""):
        flash ("Please Login!")
        return redirect(url_for('auth.login'))
    username = get_username()
    # Check if user is trying to gnerate more than one requests
    cursor.execute("SELECT status FROM leave_application WHERE employee_id = %s ORDER BY leave_id DESC", (username,))
    status = cursor.fetchone()
    if status :
        if status[0] != 'Granted' and status[0] != 'Rejected':
            flash("Can't apply For leave as last leave is pending!")
            return redirect(url_for('user.dashboard', username = username, isadmin = get_isadmin()))
    
    form = LeaveApplicationForm()
    if form.validate_on_submit():
        start_date = form.start_date.data
        end_date = form.end_date.data
        application = form.application.data
        leave_type = form.leave_type.data
        now = datetime.datetime.now()
        curr_year = int(now.year)

        cursor.execute("SELECT total_leaves_left FROM leaves_left WHERE employee_id = %s AND year = %s", (username, curr_year))
        total_leaves_left = cursor.fetchone()[0]

        leaves_demanded = int((end_date - start_date).days) + 1
        if(total_leaves_left - leaves_demanded < -10 and leave_type == "Borrowing"):
            flash ("Invalid Application! You can atmax borrow 10 leaves from upcoming year!")
            return redirect(url_for('home.error'))

        if(total_leaves_left - leaves_demanded < 0 and leave_type == "Regular"):
            flash ("Invalid Application! You can't apply for this much leaves! You can try borrowing leaves!")
            return redirect(url_for('home.error'))
        
        # Check type of Leave 
        if(total_leaves_left - leaves_demanded < 0):
            leave_type = 'Borrowing'
        else:
            leave_type = 'Regular'
        status = 'Waiting'  

        cursor.execute("SELECT end_route FROM route WHERE role = %s AND start_route = %s", (get_role(), get_role()))
        to = cursor.fetchone()

        if to is None:
            flash("Route is not defined for you! Please contact admin!")
            return redirect(url_for('home.error'))
        cursor.execute("SELECT department_id FROM employee WHERE employee_id = %s", (username,))
        department_id = cursor.fetchone()[0]
        cursor.execute("INSERT INTO leave_application(employee_id, applied_date, leave_type, start_date, end_date, status, application, department_id) VALUES(%s, %s, %s, %s, %s, %s, %s, %s)", (username, 'now()', leave_type, start_date, end_date, status, application, department_id))
        cursor.execute("SELECT leave_id FROM leave_application WHERE employee_id = %s ORDER BY leave_id DESC", (username,))
        leave_id = cursor.fetchone()[0]
        cursor.execute("INSERT INTO leave_requests(role, leave_id, department_id) VALUES(%s, %s, %s)", (to[0], leave_id, department_id))
        conn.commit()
        flash ("Application Sent!")
        return redirect(url_for('user.dashboard', username = username))
    return render_template('user/leaves/new_application.html', form=form, title="New Application" , username = username, isadmin = get_isadmin(), role = get_role())



@user.route('/myapplications', methods=['GET', 'POST'])
def my_applications():
    if (get_username() == ""):
        flash ("Please Login!")
        return redirect(url_for('auth.login'))
    username = get_username()
    cursor.execute("SELECT * FROM leave_application WHERE employee_id = %s ORDER BY leave_id DESC", (username,))
    leaves = cursor.fetchall()
    cursor.execute("SELECT * FROM comments ORDER BY leave_id DESC")
    comments = cursor.fetchall()
    cursor.execute("SELECT * FROM leaves_left WHERE employee_id = %s ORDER BY year ASC", (username,))
    leaves_left = cursor.fetchall()
    return render_template('user/leaves/my_applications.html', leaves = leaves, comments = comments, leaves_left = leaves_left, title="My Application" , username = username, isadmin = get_isadmin(), role = get_role())


@user.route('/action/<leave_id>', methods=['GET', 'POST'])
def action(leave_id):
    if (get_username() == ""):
        flash ("Please Login!")
        return redirect(url_for('auth.login'))
    username = get_username()
    form = commentFormHigher()
    cursor.execute("SELECT leave_id FROM leave_requests WHERE role = %s AND leave_id = %s", (get_role(), leave_id))
    id = cursor.fetchone()
    if id is None:
        flash ("Error : Unauthorized Access!")
        return redirect(url_for('home.error'))

    if form.validate_on_submit():
        cursor.execute("SELECT * FROM leave_application WHERE leave_id = %s ORDER BY leave_id", (leave_id,))
        leave = cursor.fetchone()
        cursor.execute("SELECT department_id FROM employee WHERE employee_id = %s", (username,))
        department_id = cursor.fetchone()
        comment = form.comment.data
        comment_by = username
        now = datetime.datetime.now()
        curr_year = int(now.year)
        comment_time = str(datetime.datetime.now())
        cursor.execute("INSERT INTO comments(leave_id, comment, comment_time, comment_by, role, department_id) VALUES(%s, %s, %s, %s, %s, %s)", (leave_id, comment, comment_time, comment_by, get_role(), department_id))
        if form.action.data == "send_back" :
            status = "Sent Back"
        elif form.action.data == "reject" :
            status = "Rejected"
        else :
            cursor.execute("Select role FROM employee WHERE employee_id = %s", (leave[2],))
            role = cursor.fetchone()[0]
            start_route = get_role()
            cursor.execute("Select end_route FROM route WHERE role = %s AND start_route = %s", (role, start_route))
            end_route = cursor.fetchone()
            if end_route is None:
                status = "Granted"
                cursor.execute("Select total_leaves_left FROM leaves_left WHERE employee_id = %s AND year = %s", (leave[2], curr_year))
                leaves_left = cursor.fetchone()[0] - int((leave[5]-leave[4]).days) - 1
                if leaves_left < 0:
                    cursor.execute("Select total_leaves_left FROM leaves_left WHERE employee_id = %s AND year = %s", (leave[2], (curr_year+1)))
                    next_leaves_left = cursor.fetchone()[0] - abs(leaves_left)
                    cursor.execute("Update leaves_left SET total_leaves_left = %s WHERE employee_id = %s AND year = %s", (next_leaves_left, leave[2], (curr_year+1)))
                    leaves_left = 0
                cursor.execute("Update leaves_left SET total_leaves_left = %s WHERE employee_id = %s AND year = %s", (leaves_left, leave[2], curr_year))
            else :
                status = "Forwarded"
                cursor.execute("DELETE FROM leave_requests WHERE role = %s AND leave_id = %s", (get_role(), leave_id))
                cursor.execute("SELECT department_id FROM employee WHERE employee_id = %s", (username,))
                department_id = cursor.fetchone()[0]
                cursor.execute("INSERT INTO leave_requests(role, leave_id, department_id) VALUES(%s, %s, %s)", (end_route, leave_id, department_id))
        if status != "Forwarded":
            cursor.execute("DELETE FROM leave_requests WHERE role = %s AND leave_id = %s", (get_role(), leave_id))
        cursor.execute("UPDATE leave_Application SET status = %s WHERE leave_id = (%s)", (status, leave[0]))
        conn.commit()
        return redirect(url_for('user.leave_requests', username = username))
    return render_template('user/leaves/action.html', leave_id = leave_id, form = form, title="Action", username = username, isadmin = get_isadmin(), role = get_role())


@user.route('/leave-requests', methods=['GET', 'POST'])
def leave_requests():
    if (get_username() == ""):
        flash ("Please Login!")
        return redirect(url_for('auth.login'))
    username = get_username()
    role=get_role()
    print(role)
    cursor.execute("SELECT leave_application.leave_id, leave_type, leave_application.employee_id, applied_date, start_date, end_date, status, application, leave_application.department_id FROM leave_application, leave_requests WHERE leave_requests.role = %s and leave_application.leave_id = leave_requests.leave_id", (get_role(),))
    temp_requests = cursor.fetchall()
    # for i in temp_requests:
    #     print(i)
    requests = []
    if get_role() == 'HOD':
        cursor.execute("SELECT department_id FROM employee WHERE employee_id = %s", (username,))
        department_id = cursor.fetchone()[0]
        for request in temp_requests:
            # print(department_id)
            if department_id == request[8]:
                requests.append(request)
    else :
        requests = temp_requests
    cursor.execute("SELECT * FROM comments ORDER BY leave_id DESC")
    comments = cursor.fetchall()
    return render_template('user/leaves/leave_requests.html', requests = requests, comments = comments, title="Leave Requests", username = username, isadmin = get_isadmin(), role = get_role())

@user.route('/comment', methods = ['GET', 'POST'])
def comment():
    if (get_username() == ""):
        flash ("Please Login!")
        return redirect(url_for('auth.login'))
    username = get_username()
    form = commentFormLower()

templates/user/leaves/action.html
{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}
    Action
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
                <h1>Action on Leave ID : {{leave_id}}</h1>
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/user/leaves/comment.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Comment{% endblock %}
{% block body %}
<section class="colorlib-education" data-section="education">
    <div class="colorlib-narrow-content">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-md-pull-3 animate-box" data-animate-effect="fadeInLeft">
                <span class="heading-meta">Action</span>
                <h2 class="colorlib-heading animate-box">Need More Comment/Clarification</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 animate-box" data-animate-effect="fadeInLeft">
                <div class="fancy-collapse-panel">
                    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="heading{{ leave[0] }}">
                                <h4 class="panel-title">
                                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ leave[0] }}" aria-expanded="false" aria-controls="collapse{{ leave[0] }}"> Leave Id : {{leave[0]}}
                                    </a>
                                </h4>
                            </div>
                            <div id="collapse{{ leave[0] }}" class="panel-collapse collapse" role="tabpanel"">
                                <div class="panel-body">
                                    <div class="center">
                                        <table class="table table-striped table-bordered">
                                            <thead>
                                                <tr>
                                                <th width="18%"> Applied Date </th>
                                                <th width="15%"> Leave Type </th>
                                                <th width="15%"> Status </th>
                                                <th width="15%"> Start Date</th>
                                                <th width="15%"> End Date </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                <td> {{ leave[3] }} </td>
                                                <td> {{ leave[1] }} </td>
                                                <td> {{ leave[6] }} </td>
                                                <td> {{ leave[4] }} </td>
                                                <td> {{ leave[5] }} </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    <hr class="intro-divider">
                                    <h3 class="headingThree", class = "center">Application</h3>
                                    <p>{{ leave[7] }}</p>
                                    </hr>
                                    <hr class="intro-divider">
                                    <h3 class="headingThree">Comments</h3>
                                    <table class="table table-striped table-bordered">
                                            <thead>
                                                <tr>
                                                <th width="30%"> Comment </th>
                                                <th width="15%"> Comment By </th>
                                                <th width="20%"> Comment Time </th>
                                                </tr>
                                            </thead>
                                            {% for comment in comments %}
                                                {% if comment[1] == leave[0] %}
                                                    <tbody>
                                                        <tr>
                                                        <td> {{ comment[2] }} </td>
                                                        <td> {{ comment[3] }} </td>
                                                        <td> {{ comment[4] }} </td>
                                                        </tr>
                                                    </tbody>
                                                {% endif %}
                                            {% endfor %}
                                        </table>
                                    </hr>
                                    <hr class="intro-divider">
                                    {{ wtf.quick_form(form) }}
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/user/leaves/leave_requests.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}My Application{% endblock %}
{% block body %}
<section class="colorlib-education" data-section="education">
    <div class="colorlib-narrow-content">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-md-pull-3 animate-box" data-animate-effect="fadeInLeft">
                <span class="heading-meta">Applications</span>
                <h2 class="colorlib-heading animate-box">Leave Requests</h2>
            </div>
        </div>
        {% if requests %}
        <div class="row">
            <div class="col-md-12 animate-box" data-animate-effect="fadeInLeft">
                <div class="fancy-collapse-panel">
                    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                        <div class="panel panel-default">
                            {% for request in requests %}
                            <div class="panel-heading" role="tab" id="heading{{ request[0] }}">
                                <h4 class="panel-title">
                                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ request[0] }}" aria-expanded="false" aria-controls="collapse{{ request[0] }}"> request Id : {{request[0]}}
                                    </a>
                                </h4>
                            </div>
                            <div id="collapse{{ request[0] }}" class="panel-collapse collapse" role="tabpanel"">
                                <div class="panel-body">
                                    <div class="center">
                                        <table class="table table-striped table-bordered">
                                            <thead>
                                                <tr>
                                                <th width="18%"> Applied Date </th>
                                                <th width="18%"> Employee ID </th>
                                                <th width="18%"> Request Type </th>
                                                <th width="15%"> Status </th>
                                                <th width="15%"> Start Date</th>
                                                <th width="15%"> End Date </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                <td> {{ request[3] }} </td>
                                                <td> {{ request[2] }} </td>
                                                <td> {{ request[1] }} </td>
                                                <td> {{ request[6] }} </td>
                                                <td> {{ request[4] }} </td>
                                                <td> {{ request[5] }} </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    <hr class="intro-divider">
                                    <h3 class="headingThree", class = "center">Application</h3>
                                    <p>{{ request[7] }}</p>
                                    </hr>
                                    <hr class="intro-divider">
                                    <h3 class="headingThree">Comments</h3>
                                    <table class="table table-striped table-bordered">
                                            <thead>
                                                <tr>
                                                <th width="30%"> Comment </th>
                                                <th width="15%"> Comment By </th>
                                                <th width="20%"> Comment Time </th>
                                                </tr>
                                            </thead>
                                            {% for comment in comments %}
                                                {% if comment[1] == request[0] %}
                                                    <tbody>
                                                        <tr>
                                                        <td> {{ comment[2] }} </td>
                                                        <td> {{ comment[3] }} </td>
                                                        <td> {{ comment[4] }} </td>
                                                        </tr>
                                                    </tbody>
                                                {% endif %}
                                            {% endfor %}
                                        </table>
                                    </hr>
                                    <hr class="intro-divider">
                                    
                                    <h3 class="headingThree">Take Action!</h3>
                                    <a href="{{ url_for('user.action', leave_id = request[0], username = request[9]) }}" class="btn btn-default btn-lg">
                                            <i class="fa fa-pencil"></i>
                                      
                                    </a>
                                    </hr>
                                </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
        <div style="text-align: center">
          <h3> No Leave Request Pending! </h3>
          <hr class="intro-divider">
        </div>
        {% endif %}
    </div>
</section>
{% endblock %}

templates/user/leaves/new_application.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Application{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
                <h1>Apply for Leave!</h1>
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}